### ISSUE TITLE
TAESD(XL?)

### ISSUE THREAD

**Issue by WASasquatch** [madebyollin/taesd#1]
With the release of Stable Diffusion XL, there is a new [VAE on the block](https://huggingface.co/stabilityai/sdxl-vae/tree/main), and it doesn't seem compatible with latent to rgb or TAESD. Are you planning to add a TAESDXL version? 

PS; Thanks for this genius idea. It's really speedy, and thus handy.

**Comment by madebyollin** [comment]
Thanks for pointing this out!

I added [new TAESDXL weights](https://github.com/madebyollin/taesd/commit/789d46c4c8a191ec9fcb20994ed0697a0cc8b4a9) compatible with the new SDXL VAE.

I haven't tested TAESDXL with SDXL itself, since the UNet weights aren't out yet, but it should hopefully Just Work.

**SDXL VAE:**
![doggo_test_sdxl](https://github.com/madebyollin/taesd/assets/8733615/0fc5bd7b-4a38-4617-92c9-11b018cd46ad)
**TAESDXL:**
![doggo_test_taesdxl](https://github.com/madebyollin/taesd/assets/8733615/e4de5309-797a-4ea2-aa3a-6e622cb322ab)

**Comment by WASasquatch** [comment]
Boss. That was fast. Thank you very much.

**Comment by comfyanonymous** [comment]
I can confirm that your new weights work with SDXL. Thank you.
